#!/usr/bin/env bash
# Teste da edição do rules.v4 feita pelo firewall.sh (sem iptables, sem root): bash deploy/relay/test-firewall.sh
set -euo pipefail
dir="$(cd "$(dirname "$0")" && pwd)"
t="$(mktemp -d)"; trap 'rm -rf "$t"' EXIT
export RULES_FILE="$t/rules.v4" SKIP_LIVE=1
L='-A INPUT -p tcp -m state --state NEW -m tcp --dport 8443 -j ACCEPT'
cat > "$RULES_FILE" <<'R'
# Generated by iptables-save
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
COMMIT
R
orig="$t/orig"; cp "$RULES_FILE" "$orig"
falha() { echo "FALHOU: $1" >&2; exit 1; }

bash "$dir/firewall.sh" >/dev/null
[[ "$(grep -cxF -- "$L" "$RULES_FILE")" == 1 ]] || falha "regra não inserida uma vez"
n=$(grep -nxF -- "$L" "$RULES_FILE" | cut -d: -f1); r=$(grep -n 'INPUT -j REJECT' "$RULES_FILE" | cut -d: -f1)
[[ "$n" == $((r - 1)) ]] || falha "regra não ficou imediatamente antes do REJECT"
diff <(grep -vxF -- "$L" "$RULES_FILE") "$orig" >/dev/null || falha "outras linhas mudaram"
ls "$t"/rules.v4.bak-* >/dev/null || falha "sem backup"

sleep 1; cp "$RULES_FILE" "$t/dep"
bash "$dir/firewall.sh" >/dev/null
cmp -s "$RULES_FILE" "$t/dep" || falha "não é idempotente"

bash "$dir/firewall.sh" --remove >/dev/null
cmp -s "$RULES_FILE" "$orig" || falha "remoção não restaurou o arquivo"
bash "$dir/firewall.sh" --remove >/dev/null
cmp -s "$RULES_FILE" "$orig" || falha "remoção repetida alterou o arquivo"

rm "$RULES_FILE"
bash "$dir/firewall.sh" 2>/dev/null >/dev/null
[[ ! -e "$RULES_FILE" ]] || falha "criou o arquivo ausente"

# --- casos multi-tabela e arquivos estranhos ---
nao_sobrou_tmp() { ! compgen -G "$t/rules.v4.??????" >/dev/null || falha "sobrou temporário"; }
rm -f "$t"/rules.v4.bak-*
caso() { printf '%b' "$2" > "$RULES_FILE"; cp "$RULES_FILE" "$orig"; echo "$1"; }
filtro='*filter\n:INPUT ACCEPT [0:0]\n-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT\n'
fim='COMMIT\n'
dentro_do_filter() { awk -v l="$L" '/^\*/{t=$1} /^COMMIT/{t=""} t=="*filter" && $0==l{n++} $0==l{tot++} END{exit !(n==1 && tot==1)}' "$RULES_FILE"; }

caso "nat antes do filter, sem REJECT" "*nat\n:PREROUTING ACCEPT [0:0]\n$fim$filtro$fim"
bash "$dir/firewall.sh" >/dev/null; dentro_do_filter || falha "nat/sem REJECT"
bash "$dir/firewall.sh" --remove >/dev/null; cmp -s "$RULES_FILE" "$orig" || falha "remove nat"

caso "REJECT de INPUT no mangle antes do filter" "*mangle\n:INPUT ACCEPT [0:0]\n-A INPUT -j REJECT\n$fim$filtro-A INPUT -j REJECT --reject-with icmp-host-prohibited\n$fim"
bash "$dir/firewall.sh" >/dev/null; dentro_do_filter || falha "mangle"
bash "$dir/firewall.sh" --remove >/dev/null; cmp -s "$RULES_FILE" "$orig" || falha "remove mangle"

caso "raw antes do filter" "*raw\n:PREROUTING ACCEPT [0:0]\n$fim$filtro-A INPUT -j REJECT\n$fim"
bash "$dir/firewall.sh" >/dev/null; dentro_do_filter || falha "raw"

caso "REJECT só em FORWARD" "$filtro-A FORWARD -j REJECT\n$fim"
bash "$dir/firewall.sh" >/dev/null; dentro_do_filter || falha "forward"
awk '/^COMMIT/{exit} {l=$0} END{}' "$RULES_FILE"
[[ "$(grep -n -xF -- "$L" "$RULES_FILE" | cut -d: -f1)" == "$(( $(grep -n '^COMMIT' "$RULES_FILE" | cut -d: -f1) - 1 ))" ]] || falha "não ficou antes do COMMIT"

caso "sem *filter" "*nat\n:PREROUTING ACCEPT [0:0]\n$fim"
rm -f "$t"/rules.v4.bak-*
if bash "$dir/firewall.sh" >/dev/null 2>&1; then falha "sem filter deveria falhar"; fi
cmp -s "$RULES_FILE" "$orig" || falha "sem filter alterou o arquivo"
compgen -G "$t/rules.v4.bak-*" >/dev/null && falha "sem filter fez backup" || true

caso "sem COMMIT" "$filtro"
if bash "$dir/firewall.sh" >/dev/null 2>&1; then falha "sem COMMIT deveria falhar"; fi
cmp -s "$RULES_FILE" "$orig" || falha "sem COMMIT alterou o arquivo"
compgen -G "$t/rules.v4.bak-*" >/dev/null && falha "sem COMMIT fez backup" || true
nao_sobrou_tmp

echo "ok: firewall.sh edita o rules.v4 corretamente"
