#!/usr/bin/env bash
# Teste da edição do rules.v4 feita pelo firewall.sh (sem iptables, sem root): bash deploy/relay/test-firewall.sh
set -euo pipefail
dir="$(cd "$(dirname "$0")" && pwd)"
t="$(mktemp -d)"; trap 'rm -rf "$t"' EXIT
export RULES_FILE="$t/rules.v4" SKIP_LIVE=1
L='-A INPUT -p tcp -m state --state NEW -m tcp --dport 8443 -j ACCEPT'
cat > "$RULES_FILE" <<'R'
# Generated by iptables-save
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
COMMIT
R
orig="$t/orig"; cp "$RULES_FILE" "$orig"
falha() { echo "FALHOU: $1" >&2; exit 1; }

bash "$dir/firewall.sh" >/dev/null
[[ "$(grep -cxF -- "$L" "$RULES_FILE")" == 1 ]] || falha "regra não inserida uma vez"
n=$(grep -nxF -- "$L" "$RULES_FILE" | cut -d: -f1); r=$(grep -n 'INPUT -j REJECT' "$RULES_FILE" | cut -d: -f1)
[[ "$n" == $((r - 1)) ]] || falha "regra não ficou imediatamente antes do REJECT"
diff <(grep -vxF -- "$L" "$RULES_FILE") "$orig" >/dev/null || falha "outras linhas mudaram"
ls "$t"/rules.v4.bak-* >/dev/null || falha "sem backup"

sleep 1; cp "$RULES_FILE" "$t/dep"
bash "$dir/firewall.sh" >/dev/null
cmp -s "$RULES_FILE" "$t/dep" || falha "não é idempotente"

bash "$dir/firewall.sh" --remove >/dev/null
cmp -s "$RULES_FILE" "$orig" || falha "remoção não restaurou o arquivo"
bash "$dir/firewall.sh" --remove >/dev/null
cmp -s "$RULES_FILE" "$orig" || falha "remoção repetida alterou o arquivo"

rm "$RULES_FILE"
bash "$dir/firewall.sh" 2>/dev/null >/dev/null
[[ ! -e "$RULES_FILE" ]] || falha "criou o arquivo ausente"
ls "$t"/rules.v4.XXXXXX >/dev/null 2>&1 && falha "sobrou temporário" || true
echo "ok: firewall.sh edita o rules.v4 corretamente"
